/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package controller;

import view.EnglishView;
import view.SwedishView;
import view.View;

/**
 * Responsible for staring the application.
 */
public class App {

  /**
   * The App starting point.
   *
   * @param args Unused program arguments.
   * @at the entry point of the application
   */
  public static void main(String[] args) throws CloneNotSupportedException {

    View view =  new EnglishView();  // new SwedishView(); 

    model.domain.LendingRegistry registry = new model.domain.LendingRegistry();

    MainController controller = new MainController();
    controller.start(registry, view);
  }
}
