/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment4;

import java.io.IOException;

/**
 * This is the generated Hello World Greeting App.
 */
public class App {

  Main main = new Main();

  /**
   * Returns a nice greeting message.
   */

  public String getGreeting() {
    return "Hello World!!";
  }


  /**
   * The App starting point.
   */
  public static void main(String[] args) throws IOException {
    App theApp = new App();
    theApp.main.startProgram();
  }
}
